# default controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [ur3_joint_1, ur3_joint_2, ur3_joint_5, ur3_joint_8, ur3_joint_9, ee_joint]

hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [ee_left_joint, ee_right_joint]

##################### WHEEL CONTROLLERS ################
front_right_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController 
  joint: "front_right_wheel_joint"
  pid : {p: 10.0, i: 0.01, d: 1.0}

rear_right_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController 
  joint: "rear_right_wheel_joint"
  pid : {p: 10.0, i: 0.01, d: 1.0} 

rear_left_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController 
  joint: "rear_left_wheel_joint"
  pid : {p: 10.0, i: 0.01, d: 1.0}

front_left_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController 
  joint: "front_left_wheel_joint"
  pid : {p: 10.0, i: 0.01, d: 1.0}